### ISSUE TITLE
Issue linking to backend

### ISSUE THREAD

**Issue by divineaverage** [divineaverage/P7_Groupomania#1]
Hello! I am redoing the redux files (using the info here: https://redux.js.org/tutorials/essentials/part-5-async-logic) but the next step is connecting it to the api. When I try to do that, it tells me:

Module not found: Error: You attempted to import ../../../../server/app which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
You can either move it inside src/, or add a symlink to it from project's node_modules/.

I tried to add a symlink but no dice. How can I resolve this error? And I know I'm not done with the redux stuff (will attack it again tomorrow) but is it on the right track now? Thanks!

**Comment by AccessiT3ch** [comment]
@divineaverage  Aaah, i think  that kind of think is more for synching state between the front end and the back end, which is not something you need to do here. As long as it looks good in the FE it should be good.

In this case the error is telling you you're trying to import something you can't, which is right bc nothing in the FE should import anything from the BE, nor visa versa :)

**Comment by divineaverage** [comment]
OMG Ok, whew. This seemed like new territory but wanted to make sure. Will backtrack - thank you!!
