### ISSUE TITLE
Card updated

### ISSUE THREAD

**Issue by divineaverage** [divineaverage/P7_Groupomania#2]
@AccessiT3ch hey hey! Updated the card, but I can't quite figure out why that post.map isn't working. After researching, I'm guessing that something in the card.jsx needs to be an array, but isn't? I've futzed with a few things but it hasn't worked so far. Am I totally off track?

**Comment by AccessiT3ch** [comment]
>  something in the card.jsx needs to be an array, but isn't?

Pretty much guaranteed something needs to be an array but isn't if we're seeing .map isn't a function, the trick is figuring out what's supposed to be an array and why it isn't one :)

**Comment by divineaverage** [comment]
Awesome, wanted to make sure I wasn't spinning wheels. To the hard-bracket
outlet I go... Ty!

**Comment by AccessiT3ch** [comment]
[Insert: Opera meme, "You get an array, YOU get an array, yes YOU get an array, EVERYBODY GETS ARRAYS!!"]

**Comment by AccessiT3ch** [comment]
@divineaverage oh no, i think a single post shouldn't be an array, ideally you have an array of posts to map over. If you `console.log(posts);` right before your return, is in an array?? As for line 54, not sure where `card` is coming from, i'm surprised you're not getting a ReferenceError by trying to reference the first item of `undefined`!

**Comment by AccessiT3ch** [comment]
@divineaverage I'm looking at your PostCard component now and it looks like you're component props aren't quite set up right, currently it's looking for a prop called "post", which doesn't exist. On line 9, if you remove the curly brackets around `post`, then `post` will be all of the props that you're passing into the component. Then I think you'll be setting it to state and deconstructing it as intended!

**Comment by divineaverage** [comment]
Ok - good call on console logging, because it's giving me "token is not valid" and I sigh. I swear this was working?

**Comment by AccessiT3ch** [comment]
>  "token is not valid"

@divineaverage maybe the token is expired? If you're persisting the store and have the same token for long enough, it'll expire. Once that happens you should be able to use your setLogout reducer to get rid of the current token and then just log in again. If it's not working after logging in then yeah something's up!
